//! Generated by Snowball 2.0.0 - https://snowballstem.org/

package danish

import (
	snowballRuntime "github.com/blevesearch/snowballstem"
)

var A_0 = []*snowballRuntime.Among{
	{Str: "hed", A: -1, B: 1, F: nil},
	{Str: "ethed", A: 0, B: 1, F: nil},
	{Str: "ered", A: -1, B: 1, F: nil},
	{Str: "e", A: -1, B: 1, F: nil},
	{Str: "erede", A: 3, B: 1, F: nil},
	{Str: "ende", A: 3, B: 1, F: nil},
	{Str: "erende", A: 5, B: 1, F: nil},
	{Str: "ene", A: 3, B: 1, F: nil},
	{Str: "erne", A: 3, B: 1, F: nil},
	{Str: "ere", A: 3, B: 1, F: nil},
	{Str: "en", A: -1, B: 1, F: nil},
	{Str: "heden", A: 10, B: 1, F: nil},
	{Str: "eren", A: 10, B: 1, F: nil},
	{Str: "er", A: -1, B: 1, F: nil},
	{Str: "heder", A: 13, B: 1, F: nil},
	{Str: "erer", A: 13, B: 1, F: nil},
	{Str: "s", A: -1, B: 2, F: nil},
	{Str: "heds", A: 16, B: 1, F: nil},
	{Str: "es", A: 16, B: 1, F: nil},
	{Str: "endes", A: 18, B: 1, F: nil},
	{Str: "erendes", A: 19, B: 1, F: nil},
	{Str: "enes", A: 18, B: 1, F: nil},
	{Str: "ernes", A: 18, B: 1, F: nil},
	{Str: "eres", A: 18, B: 1, F: nil},
	{Str: "ens", A: 16, B: 1, F: nil},
	{Str: "hedens", A: 24, B: 1, F: nil},
	{Str: "erens", A: 24, B: 1, F: nil},
	{Str: "ers", A: 16, B: 1, F: nil},
	{Str: "ets", A: 16, B: 1, F: nil},
	{Str: "erets", A: 28, B: 1, F: nil},
	{Str: "et", A: -1, B: 1, F: nil},
	{Str: "eret", A: 30, B: 1, F: nil},
}

var A_1 = []*snowballRuntime.Among{
	{Str: "gd", A: -1, B: -1, F: nil},
	{Str: "dt", A: -1, B: -1, F: nil},
	{Str: "gt", A: -1, B: -1, F: nil},
	{Str: "kt", A: -1, B: -1, F: nil},
}

var A_2 = []*snowballRuntime.Among{
	{Str: "ig", A: -1, B: 1, F: nil},
	{Str: "lig", A: 0, B: 1, F: nil},
	{Str: "elig", A: 1, B: 1, F: nil},
	{Str: "els", A: -1, B: 1, F: nil},
	{Str: "l\u00F8st", A: -1, B: 2, F: nil},
}

var G_c = []byte{119, 223, 119, 1}

var G_v = []byte{17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128}

var G_s_ending = []byte{239, 254, 42, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16}

type Context struct {
	i_x  int
	i_p1 int
	S_ch string
}

func r_mark_regions(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	context.i_p1 = env.Limit
	var v_1 = env.Cursor
	{
		var c = env.ByteIndexForHop((3))
		if int32(0) > c || c > int32(env.Limit) {
			return false
		}
		env.Cursor = int(c)
	}
	context.i_x = env.Cursor
	env.Cursor = v_1
golab0:
	for {
		var v_2 = env.Cursor
	lab1:
		for {
			if !env.InGrouping(G_v, 97, 248) {
				break lab1
			}
			env.Cursor = v_2
			break golab0
		}
		env.Cursor = v_2
		if env.Cursor >= env.Limit {
			return false
		}
		env.NextChar()
	}
golab2:
	for {
	lab3:
		for {
			if !env.OutGrouping(G_v, 97, 248) {
				break lab3
			}
			break golab2
		}
		if env.Cursor >= env.Limit {
			return false
		}
		env.NextChar()
	}
	context.i_p1 = env.Cursor
lab4:
	for {
		if !(context.i_p1 < context.i_x) {
			break lab4
		}
		context.i_p1 = context.i_x
		break lab4
	}
	return true
}

func r_main_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	if env.Cursor < context.i_p1 {
		return false
	}
	var v_2 = env.LimitBackward
	env.LimitBackward = context.i_p1
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_0, context)
	if among_var == 0 {
		env.LimitBackward = v_2
		return false
	}
	env.Bra = env.Cursor
	env.LimitBackward = v_2
	if among_var == 1 {
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !env.InGroupingB(G_s_ending, 97, 229) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func r_consonant_pair(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
	if env.Cursor < context.i_p1 {
		return false
	}
	var v_3 = env.LimitBackward
	env.LimitBackward = context.i_p1
	env.Ket = env.Cursor
	if env.FindAmongB(A_1, context) == 0 {
		env.LimitBackward = v_3
		return false
	}
	env.Bra = env.Cursor
	env.LimitBackward = v_3
	env.Cursor = env.Limit - v_1
	if env.Cursor <= env.LimitBackward {
		return false
	}
	env.PrevChar()
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_other_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if !env.EqSB("st") {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.EqSB("ig") {
			break lab0
		}
		if !env.SliceDel() {
			return false
		}
		break lab0
	}
	env.Cursor = env.Limit - v_1
	if env.Cursor < context.i_p1 {
		return false
	}
	var v_3 = env.LimitBackward
	env.LimitBackward = context.i_p1
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_2, context)
	if among_var == 0 {
		env.LimitBackward = v_3
		return false
	}
	env.Bra = env.Cursor
	env.LimitBackward = v_3
	if among_var == 1 {
		if !env.SliceDel() {
			return false
		}
		var v_4 = env.Limit - env.Cursor
		r_consonant_pair(env, context)
		env.Cursor = env.Limit - v_4
	} else if among_var == 2 {
		if !env.SliceFrom("l\u00F8s") {
			return false
		}
	}
	return true
}

func r_undouble(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if env.Cursor < context.i_p1 {
		return false
	}
	var v_2 = env.LimitBackward
	env.LimitBackward = context.i_p1
	env.Ket = env.Cursor
	if !env.InGroupingB(G_c, 98, 122) {
		env.LimitBackward = v_2
		return false
	}
	env.Bra = env.Cursor
	context.S_ch = env.SliceTo()
	if context.S_ch == "" {
		return false
	}
	env.LimitBackward = v_2
	if !env.EqSB(context.S_ch) {
		return false
	}
	if !env.SliceDel() {
		return false
	}
	return true
}

func Stem(env *snowballRuntime.Env) bool {
	var context = &Context{
		i_x:  0,
		i_p1: 0,
		S_ch: "",
	}
	_ = context
	var v_1 = env.Cursor
	r_mark_regions(env, context)
	env.Cursor = v_1
	env.LimitBackward = env.Cursor
	env.Cursor = env.Limit
	var v_2 = env.Limit - env.Cursor
	r_main_suffix(env, context)
	env.Cursor = env.Limit - v_2
	var v_3 = env.Limit - env.Cursor
	r_consonant_pair(env, context)
	env.Cursor = env.Limit - v_3
	var v_4 = env.Limit - env.Cursor
	r_other_suffix(env, context)
	env.Cursor = env.Limit - v_4
	var v_5 = env.Limit - env.Cursor
	r_undouble(env, context)
	env.Cursor = env.Limit - v_5
	env.Cursor = env.LimitBackward
	return true
}
