//! Generated by Snowball 2.0.0 - https://snowballstem.org/

package spanish

import (
	snowballRuntime "github.com/blevesearch/snowballstem"
)

var A_0 = []*snowballRuntime.Among{
	{Str: "", A: -1, B: 6, F: nil},
	{Str: "\u00E1", A: 0, B: 1, F: nil},
	{Str: "\u00E9", A: 0, B: 2, F: nil},
	{Str: "\u00ED", A: 0, B: 3, F: nil},
	{Str: "\u00F3", A: 0, B: 4, F: nil},
	{Str: "\u00FA", A: 0, B: 5, F: nil},
}

var A_1 = []*snowballRuntime.Among{
	{Str: "la", A: -1, B: -1, F: nil},
	{Str: "sela", A: 0, B: -1, F: nil},
	{Str: "le", A: -1, B: -1, F: nil},
	{Str: "me", A: -1, B: -1, F: nil},
	{Str: "se", A: -1, B: -1, F: nil},
	{Str: "lo", A: -1, B: -1, F: nil},
	{Str: "selo", A: 5, B: -1, F: nil},
	{Str: "las", A: -1, B: -1, F: nil},
	{Str: "selas", A: 7, B: -1, F: nil},
	{Str: "les", A: -1, B: -1, F: nil},
	{Str: "los", A: -1, B: -1, F: nil},
	{Str: "selos", A: 10, B: -1, F: nil},
	{Str: "nos", A: -1, B: -1, F: nil},
}

var A_2 = []*snowballRuntime.Among{
	{Str: "ando", A: -1, B: 6, F: nil},
	{Str: "iendo", A: -1, B: 6, F: nil},
	{Str: "yendo", A: -1, B: 7, F: nil},
	{Str: "\u00E1ndo", A: -1, B: 2, F: nil},
	{Str: "i\u00E9ndo", A: -1, B: 1, F: nil},
	{Str: "ar", A: -1, B: 6, F: nil},
	{Str: "er", A: -1, B: 6, F: nil},
	{Str: "ir", A: -1, B: 6, F: nil},
	{Str: "\u00E1r", A: -1, B: 3, F: nil},
	{Str: "\u00E9r", A: -1, B: 4, F: nil},
	{Str: "\u00EDr", A: -1, B: 5, F: nil},
}

var A_3 = []*snowballRuntime.Among{
	{Str: "ic", A: -1, B: -1, F: nil},
	{Str: "ad", A: -1, B: -1, F: nil},
	{Str: "os", A: -1, B: -1, F: nil},
	{Str: "iv", A: -1, B: 1, F: nil},
}

var A_4 = []*snowballRuntime.Among{
	{Str: "able", A: -1, B: 1, F: nil},
	{Str: "ible", A: -1, B: 1, F: nil},
	{Str: "ante", A: -1, B: 1, F: nil},
}

var A_5 = []*snowballRuntime.Among{
	{Str: "ic", A: -1, B: 1, F: nil},
	{Str: "abil", A: -1, B: 1, F: nil},
	{Str: "iv", A: -1, B: 1, F: nil},
}

var A_6 = []*snowballRuntime.Among{
	{Str: "ica", A: -1, B: 1, F: nil},
	{Str: "ancia", A: -1, B: 2, F: nil},
	{Str: "encia", A: -1, B: 5, F: nil},
	{Str: "adora", A: -1, B: 2, F: nil},
	{Str: "osa", A: -1, B: 1, F: nil},
	{Str: "ista", A: -1, B: 1, F: nil},
	{Str: "iva", A: -1, B: 9, F: nil},
	{Str: "anza", A: -1, B: 1, F: nil},
	{Str: "log\u00EDa", A: -1, B: 3, F: nil},
	{Str: "idad", A: -1, B: 8, F: nil},
	{Str: "able", A: -1, B: 1, F: nil},
	{Str: "ible", A: -1, B: 1, F: nil},
	{Str: "ante", A: -1, B: 2, F: nil},
	{Str: "mente", A: -1, B: 7, F: nil},
	{Str: "amente", A: 13, B: 6, F: nil},
	{Str: "aci\u00F3n", A: -1, B: 2, F: nil},
	{Str: "uci\u00F3n", A: -1, B: 4, F: nil},
	{Str: "ico", A: -1, B: 1, F: nil},
	{Str: "ismo", A: -1, B: 1, F: nil},
	{Str: "oso", A: -1, B: 1, F: nil},
	{Str: "amiento", A: -1, B: 1, F: nil},
	{Str: "imiento", A: -1, B: 1, F: nil},
	{Str: "ivo", A: -1, B: 9, F: nil},
	{Str: "ador", A: -1, B: 2, F: nil},
	{Str: "icas", A: -1, B: 1, F: nil},
	{Str: "ancias", A: -1, B: 2, F: nil},
	{Str: "encias", A: -1, B: 5, F: nil},
	{Str: "adoras", A: -1, B: 2, F: nil},
	{Str: "osas", A: -1, B: 1, F: nil},
	{Str: "istas", A: -1, B: 1, F: nil},
	{Str: "ivas", A: -1, B: 9, F: nil},
	{Str: "anzas", A: -1, B: 1, F: nil},
	{Str: "log\u00EDas", A: -1, B: 3, F: nil},
	{Str: "idades", A: -1, B: 8, F: nil},
	{Str: "ables", A: -1, B: 1, F: nil},
	{Str: "ibles", A: -1, B: 1, F: nil},
	{Str: "aciones", A: -1, B: 2, F: nil},
	{Str: "uciones", A: -1, B: 4, F: nil},
	{Str: "adores", A: -1, B: 2, F: nil},
	{Str: "antes", A: -1, B: 2, F: nil},
	{Str: "icos", A: -1, B: 1, F: nil},
	{Str: "ismos", A: -1, B: 1, F: nil},
	{Str: "osos", A: -1, B: 1, F: nil},
	{Str: "amientos", A: -1, B: 1, F: nil},
	{Str: "imientos", A: -1, B: 1, F: nil},
	{Str: "ivos", A: -1, B: 9, F: nil},
}

var A_7 = []*snowballRuntime.Among{
	{Str: "ya", A: -1, B: 1, F: nil},
	{Str: "ye", A: -1, B: 1, F: nil},
	{Str: "yan", A: -1, B: 1, F: nil},
	{Str: "yen", A: -1, B: 1, F: nil},
	{Str: "yeron", A: -1, B: 1, F: nil},
	{Str: "yendo", A: -1, B: 1, F: nil},
	{Str: "yo", A: -1, B: 1, F: nil},
	{Str: "yas", A: -1, B: 1, F: nil},
	{Str: "yes", A: -1, B: 1, F: nil},
	{Str: "yais", A: -1, B: 1, F: nil},
	{Str: "yamos", A: -1, B: 1, F: nil},
	{Str: "y\u00F3", A: -1, B: 1, F: nil},
}

var A_8 = []*snowballRuntime.Among{
	{Str: "aba", A: -1, B: 2, F: nil},
	{Str: "ada", A: -1, B: 2, F: nil},
	{Str: "ida", A: -1, B: 2, F: nil},
	{Str: "ara", A: -1, B: 2, F: nil},
	{Str: "iera", A: -1, B: 2, F: nil},
	{Str: "\u00EDa", A: -1, B: 2, F: nil},
	{Str: "ar\u00EDa", A: 5, B: 2, F: nil},
	{Str: "er\u00EDa", A: 5, B: 2, F: nil},
	{Str: "ir\u00EDa", A: 5, B: 2, F: nil},
	{Str: "ad", A: -1, B: 2, F: nil},
	{Str: "ed", A: -1, B: 2, F: nil},
	{Str: "id", A: -1, B: 2, F: nil},
	{Str: "ase", A: -1, B: 2, F: nil},
	{Str: "iese", A: -1, B: 2, F: nil},
	{Str: "aste", A: -1, B: 2, F: nil},
	{Str: "iste", A: -1, B: 2, F: nil},
	{Str: "an", A: -1, B: 2, F: nil},
	{Str: "aban", A: 16, B: 2, F: nil},
	{Str: "aran", A: 16, B: 2, F: nil},
	{Str: "ieran", A: 16, B: 2, F: nil},
	{Str: "\u00EDan", A: 16, B: 2, F: nil},
	{Str: "ar\u00EDan", A: 20, B: 2, F: nil},
	{Str: "er\u00EDan", A: 20, B: 2, F: nil},
	{Str: "ir\u00EDan", A: 20, B: 2, F: nil},
	{Str: "en", A: -1, B: 1, F: nil},
	{Str: "asen", A: 24, B: 2, F: nil},
	{Str: "iesen", A: 24, B: 2, F: nil},
	{Str: "aron", A: -1, B: 2, F: nil},
	{Str: "ieron", A: -1, B: 2, F: nil},
	{Str: "ar\u00E1n", A: -1, B: 2, F: nil},
	{Str: "er\u00E1n", A: -1, B: 2, F: nil},
	{Str: "ir\u00E1n", A: -1, B: 2, F: nil},
	{Str: "ado", A: -1, B: 2, F: nil},
	{Str: "ido", A: -1, B: 2, F: nil},
	{Str: "ando", A: -1, B: 2, F: nil},
	{Str: "iendo", A: -1, B: 2, F: nil},
	{Str: "ar", A: -1, B: 2, F: nil},
	{Str: "er", A: -1, B: 2, F: nil},
	{Str: "ir", A: -1, B: 2, F: nil},
	{Str: "as", A: -1, B: 2, F: nil},
	{Str: "abas", A: 39, B: 2, F: nil},
	{Str: "adas", A: 39, B: 2, F: nil},
	{Str: "idas", A: 39, B: 2, F: nil},
	{Str: "aras", A: 39, B: 2, F: nil},
	{Str: "ieras", A: 39, B: 2, F: nil},
	{Str: "\u00EDas", A: 39, B: 2, F: nil},
	{Str: "ar\u00EDas", A: 45, B: 2, F: nil},
	{Str: "er\u00EDas", A: 45, B: 2, F: nil},
	{Str: "ir\u00EDas", A: 45, B: 2, F: nil},
	{Str: "es", A: -1, B: 1, F: nil},
	{Str: "ases", A: 49, B: 2, F: nil},
	{Str: "ieses", A: 49, B: 2, F: nil},
	{Str: "abais", A: -1, B: 2, F: nil},
	{Str: "arais", A: -1, B: 2, F: nil},
	{Str: "ierais", A: -1, B: 2, F: nil},
	{Str: "\u00EDais", A: -1, B: 2, F: nil},
	{Str: "ar\u00EDais", A: 55, B: 2, F: nil},
	{Str: "er\u00EDais", A: 55, B: 2, F: nil},
	{Str: "ir\u00EDais", A: 55, B: 2, F: nil},
	{Str: "aseis", A: -1, B: 2, F: nil},
	{Str: "ieseis", A: -1, B: 2, F: nil},
	{Str: "asteis", A: -1, B: 2, F: nil},
	{Str: "isteis", A: -1, B: 2, F: nil},
	{Str: "\u00E1is", A: -1, B: 2, F: nil},
	{Str: "\u00E9is", A: -1, B: 1, F: nil},
	{Str: "ar\u00E9is", A: 64, B: 2, F: nil},
	{Str: "er\u00E9is", A: 64, B: 2, F: nil},
	{Str: "ir\u00E9is", A: 64, B: 2, F: nil},
	{Str: "ados", A: -1, B: 2, F: nil},
	{Str: "idos", A: -1, B: 2, F: nil},
	{Str: "amos", A: -1, B: 2, F: nil},
	{Str: "\u00E1bamos", A: 70, B: 2, F: nil},
	{Str: "\u00E1ramos", A: 70, B: 2, F: nil},
	{Str: "i\u00E9ramos", A: 70, B: 2, F: nil},
	{Str: "\u00EDamos", A: 70, B: 2, F: nil},
	{Str: "ar\u00EDamos", A: 74, B: 2, F: nil},
	{Str: "er\u00EDamos", A: 74, B: 2, F: nil},
	{Str: "ir\u00EDamos", A: 74, B: 2, F: nil},
	{Str: "emos", A: -1, B: 1, F: nil},
	{Str: "aremos", A: 78, B: 2, F: nil},
	{Str: "eremos", A: 78, B: 2, F: nil},
	{Str: "iremos", A: 78, B: 2, F: nil},
	{Str: "\u00E1semos", A: 78, B: 2, F: nil},
	{Str: "i\u00E9semos", A: 78, B: 2, F: nil},
	{Str: "imos", A: -1, B: 2, F: nil},
	{Str: "ar\u00E1s", A: -1, B: 2, F: nil},
	{Str: "er\u00E1s", A: -1, B: 2, F: nil},
	{Str: "ir\u00E1s", A: -1, B: 2, F: nil},
	{Str: "\u00EDs", A: -1, B: 2, F: nil},
	{Str: "ar\u00E1", A: -1, B: 2, F: nil},
	{Str: "er\u00E1", A: -1, B: 2, F: nil},
	{Str: "ir\u00E1", A: -1, B: 2, F: nil},
	{Str: "ar\u00E9", A: -1, B: 2, F: nil},
	{Str: "er\u00E9", A: -1, B: 2, F: nil},
	{Str: "ir\u00E9", A: -1, B: 2, F: nil},
	{Str: "i\u00F3", A: -1, B: 2, F: nil},
}

var A_9 = []*snowballRuntime.Among{
	{Str: "a", A: -1, B: 1, F: nil},
	{Str: "e", A: -1, B: 2, F: nil},
	{Str: "o", A: -1, B: 1, F: nil},
	{Str: "os", A: -1, B: 1, F: nil},
	{Str: "\u00E1", A: -1, B: 1, F: nil},
	{Str: "\u00E9", A: -1, B: 2, F: nil},
	{Str: "\u00ED", A: -1, B: 1, F: nil},
	{Str: "\u00F3", A: -1, B: 1, F: nil},
}

var G_v = []byte{17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 17, 4, 10}

type Context struct {
	i_p2 int
	i_p1 int
	i_pV int
}

func r_mark_regions(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	context.i_pV = env.Limit
	context.i_p1 = env.Limit
	context.i_p2 = env.Limit
	var v_1 = env.Cursor
lab0:
	for {
	lab1:
		for {
			var v_2 = env.Cursor
		lab2:
			for {
				if !env.InGrouping(G_v, 97, 252) {
					break lab2
				}
			lab3:
				for {
					var v_3 = env.Cursor
				lab4:
					for {
						if !env.OutGrouping(G_v, 97, 252) {
							break lab4
						}
					golab5:
						for {
						lab6:
							for {
								if !env.InGrouping(G_v, 97, 252) {
									break lab6
								}
								break golab5
							}
							if env.Cursor >= env.Limit {
								break lab4
							}
							env.NextChar()
						}
						break lab3
					}
					env.Cursor = v_3
					if !env.InGrouping(G_v, 97, 252) {
						break lab2
					}
				golab7:
					for {
					lab8:
						for {
							if !env.OutGrouping(G_v, 97, 252) {
								break lab8
							}
							break golab7
						}
						if env.Cursor >= env.Limit {
							break lab2
						}
						env.NextChar()
					}
					break lab3
				}
				break lab1
			}
			env.Cursor = v_2
			if !env.OutGrouping(G_v, 97, 252) {
				break lab0
			}
		lab9:
			for {
				var v_6 = env.Cursor
			lab10:
				for {
					if !env.OutGrouping(G_v, 97, 252) {
						break lab10
					}
				golab11:
					for {
					lab12:
						for {
							if !env.InGrouping(G_v, 97, 252) {
								break lab12
							}
							break golab11
						}
						if env.Cursor >= env.Limit {
							break lab10
						}
						env.NextChar()
					}
					break lab9
				}
				env.Cursor = v_6
				if !env.InGrouping(G_v, 97, 252) {
					break lab0
				}
				if env.Cursor >= env.Limit {
					break lab0
				}
				env.NextChar()
				break lab9
			}
			break lab1
		}
		context.i_pV = env.Cursor
		break lab0
	}
	env.Cursor = v_1
	var v_8 = env.Cursor
lab13:
	for {
	golab14:
		for {
		lab15:
			for {
				if !env.InGrouping(G_v, 97, 252) {
					break lab15
				}
				break golab14
			}
			if env.Cursor >= env.Limit {
				break lab13
			}
			env.NextChar()
		}
	golab16:
		for {
		lab17:
			for {
				if !env.OutGrouping(G_v, 97, 252) {
					break lab17
				}
				break golab16
			}
			if env.Cursor >= env.Limit {
				break lab13
			}
			env.NextChar()
		}
		context.i_p1 = env.Cursor
	golab18:
		for {
		lab19:
			for {
				if !env.InGrouping(G_v, 97, 252) {
					break lab19
				}
				break golab18
			}
			if env.Cursor >= env.Limit {
				break lab13
			}
			env.NextChar()
		}
	golab20:
		for {
		lab21:
			for {
				if !env.OutGrouping(G_v, 97, 252) {
					break lab21
				}
				break golab20
			}
			if env.Cursor >= env.Limit {
				break lab13
			}
			env.NextChar()
		}
		context.i_p2 = env.Cursor
		break lab13
	}
	env.Cursor = v_8
	return true
}

func r_postlude(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
replab0:
	for {
		var v_1 = env.Cursor
	lab1:
		for range [2]struct{}{} {
			env.Bra = env.Cursor
			among_var = env.FindAmong(A_0, context)
			if among_var == 0 {
				break lab1
			}
			env.Ket = env.Cursor
			if among_var == 1 {
				if !env.SliceFrom("a") {
					return false
				}
			} else if among_var == 2 {
				if !env.SliceFrom("e") {
					return false
				}
			} else if among_var == 3 {
				if !env.SliceFrom("i") {
					return false
				}
			} else if among_var == 4 {
				if !env.SliceFrom("o") {
					return false
				}
			} else if among_var == 5 {
				if !env.SliceFrom("u") {
					return false
				}
			} else if among_var == 6 {
				if env.Cursor >= env.Limit {
					break lab1
				}
				env.NextChar()
			}
			continue replab0
		}
		env.Cursor = v_1
		break replab0
	}
	return true
}

func r_RV(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if !(context.i_pV <= env.Cursor) {
		return false
	}
	return true
}

func r_R1(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if !(context.i_p1 <= env.Cursor) {
		return false
	}
	return true
}

func r_R2(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if !(context.i_p2 <= env.Cursor) {
		return false
	}
	return true
}

func r_attached_pronoun(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	if env.FindAmongB(A_1, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	among_var = env.FindAmongB(A_2, context)
	if among_var == 0 {
		return false
	}
	if !r_RV(env, context) {
		return false
	}
	if among_var == 1 {
		env.Bra = env.Cursor
		if !env.SliceFrom("iendo") {
			return false
		}
	} else if among_var == 2 {
		env.Bra = env.Cursor
		if !env.SliceFrom("ando") {
			return false
		}
	} else if among_var == 3 {
		env.Bra = env.Cursor
		if !env.SliceFrom("ar") {
			return false
		}
	} else if among_var == 4 {
		env.Bra = env.Cursor
		if !env.SliceFrom("er") {
			return false
		}
	} else if among_var == 5 {
		env.Bra = env.Cursor
		if !env.SliceFrom("ir") {
			return false
		}
	} else if among_var == 6 {
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 7 {
		if !env.EqSB("u") {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func r_standard_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_6, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_1 = env.Limit - env.Cursor
	lab0:
		for {
			env.Ket = env.Cursor
			if !env.EqSB("ic") {
				env.Cursor = env.Limit - v_1
				break lab0
			}
			env.Bra = env.Cursor
			if !r_R2(env, context) {
				env.Cursor = env.Limit - v_1
				break lab0
			}
			if !env.SliceDel() {
				return false
			}
			break lab0
		}
	} else if among_var == 3 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceFrom("log") {
			return false
		}
	} else if among_var == 4 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceFrom("u") {
			return false
		}
	} else if among_var == 5 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceFrom("ente") {
			return false
		}
	} else if among_var == 6 {
		if !r_R1(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_2 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			among_var = env.FindAmongB(A_3, context)
			if among_var == 0 {
				env.Cursor = env.Limit - v_2
				break lab1
			}
			env.Bra = env.Cursor
			if !r_R2(env, context) {
				env.Cursor = env.Limit - v_2
				break lab1
			}
			if !env.SliceDel() {
				return false
			}
			if among_var == 1 {
				env.Ket = env.Cursor
				if !env.EqSB("at") {
					env.Cursor = env.Limit - v_2
					break lab1
				}
				env.Bra = env.Cursor
				if !r_R2(env, context) {
					env.Cursor = env.Limit - v_2
					break lab1
				}
				if !env.SliceDel() {
					return false
				}
			}
			break lab1
		}
	} else if among_var == 7 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_3 = env.Limit - env.Cursor
	lab2:
		for {
			env.Ket = env.Cursor
			if env.FindAmongB(A_4, context) == 0 {
				env.Cursor = env.Limit - v_3
				break lab2
			}
			env.Bra = env.Cursor
			if !r_R2(env, context) {
				env.Cursor = env.Limit - v_3
				break lab2
			}
			if !env.SliceDel() {
				return false
			}
			break lab2
		}
	} else if among_var == 8 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_4 = env.Limit - env.Cursor
	lab3:
		for {
			env.Ket = env.Cursor
			if env.FindAmongB(A_5, context) == 0 {
				env.Cursor = env.Limit - v_4
				break lab3
			}
			env.Bra = env.Cursor
			if !r_R2(env, context) {
				env.Cursor = env.Limit - v_4
				break lab3
			}
			if !env.SliceDel() {
				return false
			}
			break lab3
		}
	} else if among_var == 9 {
		if !r_R2(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_5 = env.Limit - env.Cursor
	lab4:
		for {
			env.Ket = env.Cursor
			if !env.EqSB("at") {
				env.Cursor = env.Limit - v_5
				break lab4
			}
			env.Bra = env.Cursor
			if !r_R2(env, context) {
				env.Cursor = env.Limit - v_5
				break lab4
			}
			if !env.SliceDel() {
				return false
			}
			break lab4
		}
	}
	return true
}

func r_y_verb_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if env.Cursor < context.i_pV {
		return false
	}
	var v_2 = env.LimitBackward
	env.LimitBackward = context.i_pV
	env.Ket = env.Cursor
	if env.FindAmongB(A_7, context) == 0 {
		env.LimitBackward = v_2
		return false
	}
	env.Bra = env.Cursor
	env.LimitBackward = v_2
	if !env.EqSB("u") {
		return false
	}
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_verb_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	if env.Cursor < context.i_pV {
		return false
	}
	var v_2 = env.LimitBackward
	env.LimitBackward = context.i_pV
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_8, context)
	if among_var == 0 {
		env.LimitBackward = v_2
		return false
	}
	env.Bra = env.Cursor
	env.LimitBackward = v_2
	if among_var == 1 {
		var v_3 = env.Limit - env.Cursor
	lab0:
		for {
			if !env.EqSB("u") {
				env.Cursor = env.Limit - v_3
				break lab0
			}
			var v_4 = env.Limit - env.Cursor
			if !env.EqSB("g") {
				env.Cursor = env.Limit - v_3
				break lab0
			}
			env.Cursor = env.Limit - v_4
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !env.SliceDel() {
			return false
		}
	}
	return true
}

func r_residual_suffix(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_9, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
		if !r_RV(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
	} else if among_var == 2 {
		if !r_RV(env, context) {
			return false
		}
		if !env.SliceDel() {
			return false
		}
		var v_1 = env.Limit - env.Cursor
	lab0:
		for {
			env.Ket = env.Cursor
			if !env.EqSB("u") {
				env.Cursor = env.Limit - v_1
				break lab0
			}
			env.Bra = env.Cursor
			var v_2 = env.Limit - env.Cursor
			if !env.EqSB("g") {
				env.Cursor = env.Limit - v_1
				break lab0
			}
			env.Cursor = env.Limit - v_2
			if !r_RV(env, context) {
				env.Cursor = env.Limit - v_1
				break lab0
			}
			if !env.SliceDel() {
				return false
			}
			break lab0
		}
	}
	return true
}

func Stem(env *snowballRuntime.Env) bool {
	var context = &Context{
		i_p2: 0,
		i_p1: 0,
		i_pV: 0,
	}
	_ = context
	r_mark_regions(env, context)
	env.LimitBackward = env.Cursor
	env.Cursor = env.Limit
	var v_2 = env.Limit - env.Cursor
	r_attached_pronoun(env, context)
	env.Cursor = env.Limit - v_2
	var v_3 = env.Limit - env.Cursor
lab0:
	for {
	lab1:
		for {
			var v_4 = env.Limit - env.Cursor
		lab2:
			for {
				if !r_standard_suffix(env, context) {
					break lab2
				}
				break lab1
			}
			env.Cursor = env.Limit - v_4
		lab3:
			for {
				if !r_y_verb_suffix(env, context) {
					break lab3
				}
				break lab1
			}
			env.Cursor = env.Limit - v_4
			if !r_verb_suffix(env, context) {
				break lab0
			}
			break lab1
		}
		break lab0
	}
	env.Cursor = env.Limit - v_3
	var v_5 = env.Limit - env.Cursor
	r_residual_suffix(env, context)
	env.Cursor = env.Limit - v_5
	env.Cursor = env.LimitBackward
	var v_6 = env.Cursor
	r_postlude(env, context)
	env.Cursor = v_6
	return true
}
