//! Generated by Snowball 2.0.0 - https://snowballstem.org/

package greek

import (
	snowballRuntime "github.com/blevesearch/snowballstem"
)

var A_0 = []*snowballRuntime.Among{
	{Str: "", A: -1, B: 25, F: nil},
	{Str: "\u03C2", A: 0, B: 18, F: nil},
	{Str: "\u0386", A: 0, B: 1, F: nil},
	{Str: "\u0388", A: 0, B: 5, F: nil},
	{Str: "\u0389", A: 0, B: 7, F: nil},
	{Str: "\u038A", A: 0, B: 9, F: nil},
	{Str: "\u03CA", A: 0, B: 7, F: nil},
	{Str: "\u03CB", A: 0, B: 20, F: nil},
	{Str: "\u038C", A: 0, B: 15, F: nil},
	{Str: "\u03CC", A: 0, B: 15, F: nil},
	{Str: "\u03CD", A: 0, B: 20, F: nil},
	{Str: "\u038E", A: 0, B: 20, F: nil},
	{Str: "\u03CE", A: 0, B: 24, F: nil},
	{Str: "\u038F", A: 0, B: 24, F: nil},
	{Str: "\u0390", A: 0, B: 7, F: nil},
	{Str: "\u0391", A: 0, B: 1, F: nil},
	{Str: "\u0392", A: 0, B: 2, F: nil},
	{Str: "\u0393", A: 0, B: 3, F: nil},
	{Str: "\u0394", A: 0, B: 4, F: nil},
	{Str: "\u0395", A: 0, B: 5, F: nil},
	{Str: "\u0396", A: 0, B: 6, F: nil},
	{Str: "\u0397", A: 0, B: 7, F: nil},
	{Str: "\u0398", A: 0, B: 8, F: nil},
	{Str: "\u0399", A: 0, B: 9, F: nil},
	{Str: "\u039A", A: 0, B: 10, F: nil},
	{Str: "\u039B", A: 0, B: 11, F: nil},
	{Str: "\u039C", A: 0, B: 12, F: nil},
	{Str: "\u039D", A: 0, B: 13, F: nil},
	{Str: "\u039E", A: 0, B: 14, F: nil},
	{Str: "\u039F", A: 0, B: 15, F: nil},
	{Str: "\u03A0", A: 0, B: 16, F: nil},
	{Str: "\u03A1", A: 0, B: 17, F: nil},
	{Str: "\u03A3", A: 0, B: 18, F: nil},
	{Str: "\u03A4", A: 0, B: 19, F: nil},
	{Str: "\u03A5", A: 0, B: 20, F: nil},
	{Str: "\u03A6", A: 0, B: 21, F: nil},
	{Str: "\u03A7", A: 0, B: 22, F: nil},
	{Str: "\u03A8", A: 0, B: 23, F: nil},
	{Str: "\u03A9", A: 0, B: 24, F: nil},
	{Str: "\u03AA", A: 0, B: 9, F: nil},
	{Str: "\u03AB", A: 0, B: 20, F: nil},
	{Str: "\u03AC", A: 0, B: 1, F: nil},
	{Str: "\u03AD", A: 0, B: 5, F: nil},
	{Str: "\u03AE", A: 0, B: 7, F: nil},
	{Str: "\u03AF", A: 0, B: 9, F: nil},
	{Str: "\u03B0", A: 0, B: 20, F: nil},
}

var A_1 = []*snowballRuntime.Among{
	{Str: "\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C3", A: -1, B: 10, F: nil},
	{Str: "\u03C6\u03C9\u03C3", A: -1, B: 9, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B1\u03C3", A: -1, B: 7, F: nil},
	{Str: "\u03C4\u03B5\u03C1\u03B1\u03C3", A: -1, B: 8, F: nil},
	{Str: "\u03BA\u03C1\u03B5\u03B1\u03C3", A: -1, B: 6, F: nil},
	{Str: "\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03BF\u03C3", A: -1, B: 10, F: nil},
	{Str: "\u03C6\u03C9\u03C4\u03BF\u03C3", A: -1, B: 9, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B1\u03C4\u03BF\u03C3", A: -1, B: 7, F: nil},
	{Str: "\u03C4\u03B5\u03C1\u03B1\u03C4\u03BF\u03C3", A: -1, B: 8, F: nil},
	{Str: "\u03BA\u03C1\u03B5\u03B1\u03C4\u03BF\u03C3", A: -1, B: 6, F: nil},
	{Str: "\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03BF\u03C3", A: -1, B: 11, F: nil},
	{Str: "\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C3", A: -1, B: 11, F: nil},
	{Str: "\u03C6\u03B1\u03B3\u03B9\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03B1\u03B3\u03B9\u03BF\u03C5", A: -1, B: 2, F: nil},
	{Str: "\u03C3\u03BF\u03B3\u03B9\u03BF\u03C5", A: -1, B: 4, F: nil},
	{Str: "\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03BF\u03C5", A: -1, B: 5, F: nil},
	{Str: "\u03BF\u03BB\u03BF\u03B3\u03B9\u03BF\u03C5", A: -1, B: 3, F: nil},
	{Str: "\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03B1", A: -1, B: 10, F: nil},
	{Str: "\u03C6\u03C9\u03C4\u03B1", A: -1, B: 9, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B1\u03C4\u03B1", A: -1, B: 7, F: nil},
	{Str: "\u03C4\u03B5\u03C1\u03B1\u03C4\u03B1", A: -1, B: 8, F: nil},
	{Str: "\u03BA\u03C1\u03B5\u03B1\u03C4\u03B1", A: -1, B: 6, F: nil},
	{Str: "\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03B1", A: -1, B: 11, F: nil},
	{Str: "\u03C6\u03B1\u03B3\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03B1\u03B3\u03B9\u03B1", A: -1, B: 2, F: nil},
	{Str: "\u03C3\u03BF\u03B3\u03B9\u03B1", A: -1, B: 4, F: nil},
	{Str: "\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03B1", A: -1, B: 5, F: nil},
	{Str: "\u03BF\u03BB\u03BF\u03B3\u03B9\u03B1", A: -1, B: 3, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B1\u03C4\u03B7", A: -1, B: 7, F: nil},
	{Str: "\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4\u03C9\u03C4\u03C9\u03BD", A: -1, B: 10, F: nil},
	{Str: "\u03C6\u03C9\u03C4\u03C9\u03BD", A: -1, B: 9, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B1\u03C4\u03C9\u03BD", A: -1, B: 7, F: nil},
	{Str: "\u03C4\u03B5\u03C1\u03B1\u03C4\u03C9\u03BD", A: -1, B: 8, F: nil},
	{Str: "\u03BA\u03C1\u03B5\u03B1\u03C4\u03C9\u03BD", A: -1, B: 6, F: nil},
	{Str: "\u03B3\u03B5\u03B3\u03BF\u03BD\u03BF\u03C4\u03C9\u03BD", A: -1, B: 11, F: nil},
	{Str: "\u03C6\u03B1\u03B3\u03B9\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03B1\u03B3\u03B9\u03C9\u03BD", A: -1, B: 2, F: nil},
	{Str: "\u03C3\u03BF\u03B3\u03B9\u03C9\u03BD", A: -1, B: 4, F: nil},
	{Str: "\u03C4\u03B1\u03C4\u03BF\u03B3\u03B9\u03C9\u03BD", A: -1, B: 5, F: nil},
	{Str: "\u03BF\u03BB\u03BF\u03B3\u03B9\u03C9\u03BD", A: -1, B: 3, F: nil},
}

var A_2 = []*snowballRuntime.Among{
	{Str: "\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B1", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03BC\u03C0\u03B1", A: 0, B: 1, F: nil},
	{Str: "\u03B4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B8\u03C1\u03BF", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", A: 7, B: 1, F: nil},
}

var A_3 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BC\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03C1", A: 3, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B3\u03BB\u03C5\u03BA\u03C5\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BB\u03C5\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03C0\u03B1\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B3\u03BA\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03C0\u03B5\u03C1\u03BF\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B2\u03BF\u03BB\u03B2\u03BF\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B3\u03BB\u03C5\u03BA\u03BF\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03BB\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03B8\u03C5\u03C1\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03C1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03C1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03C1\u03BD", A: -1, B: 1, F: nil},
}

var A_4 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03B6\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B5\u03B9\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03C9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B1\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B5\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03BF\u03C5\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03BF\u03C5\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B5\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03BF\u03C5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B6\u03B1\u03BD", A: -1, B: 1, F: nil},
}

var A_5 = []*snowballRuntime.Among{
	{Str: "\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C8", A: -1, B: 1, F: nil},
	{Str: "\u03B6\u03C9", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BD", A: -1, B: 1, F: nil},
}

var A_6 = []*snowballRuntime.Among{
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B1\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03B8\u03B7\u03BA\u03B1\u03BD", A: -1, B: 1, F: nil},
}

var A_7 = []*snowballRuntime.Among{
	{Str: "\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BC\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03C1\u03C4\u03BF\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BE\u03B1\u03C1\u03C7\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B5", A: 7, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03C4\u03B5\u03C0\u03B5", A: 8, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B5\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03B5\u03BA\u03BB\u03B5", A: 13, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B8\u03C1\u03BF", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", A: 17, B: 1, F: nil},
}

var A_8 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B7\u03BC\u03BF\u03BA\u03C1\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B9\u03B3\u03B1\u03BD\u03C4\u03BF\u03B1\u03C6", A: 3, B: 1, F: nil},
	{Str: "\u03B3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03BA\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03C5\u03BA\u03B1\u03BC", A: 8, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03BC", A: 8, B: 1, F: nil},
	{Str: "\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03BB\u03BF", A: -1, B: 1, F: nil},
}

var A_9 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C3\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B1\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B1\u03BD", A: -1, B: 1, F: nil},
}

var A_10 = []*snowballRuntime.Among{
	{Str: "\u03BE\u03B1\u03BD\u03B1\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B9\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B1\u03BC\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BC\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03C1\u03C4\u03BF\u03C0\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BE\u03B1\u03C1\u03C7\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B5", A: 7, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03C4\u03B5\u03C0\u03B5", A: 8, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B5\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03B5\u03BA\u03BB\u03B5", A: 13, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", A: 11, B: 1, F: nil},
	{Str: "\u03B4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B8\u03C1\u03BF", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", A: 17, B: 1, F: nil},
}

var A_11 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C3\u03B5\u03B9\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B5\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BF\u03C5\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BF\u03C5\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03B5\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BF\u03C5\u03BD", A: -1, B: 1, F: nil},
}

var A_12 = []*snowballRuntime.Among{
	{Str: "\u03C3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03B5", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03C9\u03BA\u03BB\u03B5", A: 3, B: 1, F: nil},
	{Str: "\u03B4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B1\u03B8\u03C1\u03BF", A: -1, B: 1, F: nil},
}

var A_13 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C5\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03BC\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B3\u03C5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03C9\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BF\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C7\u03C4", A: 9, B: 1, F: nil},
	{Str: "\u03BA\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BA\u03C4", A: 11, B: 1, F: nil},
	{Str: "\u03C3\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03C7", A: 13, B: 1, F: nil},
	{Str: "\u03C4\u03B1\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C4\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C6\u03B1", A: 18, B: 1, F: nil},
	{Str: "\u03BB\u03C5\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C7\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B9\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B5\u03BC", A: 30, B: 1, F: nil},
	{Str: "\u03B1\u03C7\u03BD", A: -1, B: 1, F: nil},
}

var A_14 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C3\u03C4\u03BF\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03B7\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03B7", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03BF\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03C4\u03BF", A: -1, B: 1, F: nil},
}

var A_15 = []*snowballRuntime.Among{
	{Str: "\u03C3\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03C4\u03B1\u03C3\u03B5", A: 0, B: 1, F: nil},
	{Str: "\u03BC\u03B9\u03BA\u03C1\u03BF\u03C3\u03B5", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03B3\u03BA\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03BA\u03BB\u03B5", A: -1, B: 1, F: nil},
}

var A_16 = []*snowballRuntime.Among{
	{Str: "\u03B4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03C4\u03B9\u03B4\u03B1\u03BD\u03B5", A: 0, B: 1, F: nil},
}

var A_17 = []*snowballRuntime.Among{
	{Str: "\u03C4\u03BF\u03C0\u03B9\u03BA", A: -1, B: 7, F: nil},
	{Str: "\u03C3\u03BA\u03B5\u03C0\u03C4\u03B9\u03BA", A: -1, B: 6, F: nil},
	{Str: "\u03B3\u03BD\u03C9\u03C3\u03C4\u03B9\u03BA", A: -1, B: 3, F: nil},
	{Str: "\u03B1\u03B3\u03BD\u03C9\u03C3\u03C4\u03B9\u03BA", A: 2, B: 1, F: nil},
	{Str: "\u03B5\u03BA\u03BB\u03B5\u03BA\u03C4\u03B9\u03BA", A: -1, B: 5, F: nil},
	{Str: "\u03B1\u03C4\u03BF\u03BC\u03B9\u03BA", A: -1, B: 2, F: nil},
	{Str: "\u03B5\u03B8\u03BD\u03B9\u03BA", A: -1, B: 4, F: nil},
	{Str: "\u03B8\u03B5\u03B1\u03C4\u03C1\u03B9\u03BD", A: -1, B: 10, F: nil},
	{Str: "\u03B1\u03BB\u03B5\u03BE\u03B1\u03BD\u03B4\u03C1\u03B9\u03BD", A: -1, B: 8, F: nil},
	{Str: "\u03B2\u03C5\u03B6\u03B1\u03BD\u03C4\u03B9\u03BD", A: -1, B: 9, F: nil},
}

var A_18 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C3\u03BC\u03BF\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BC\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BC\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BC\u03BF\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BC\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BC\u03BF", A: -1, B: 1, F: nil},
}

var A_19 = []*snowballRuntime.Among{
	{Str: "\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
}

var A_20 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03C1\u03B1\u03BA\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03B4\u03B1\u03BA\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03B1\u03BA\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03B4\u03B1\u03BA\u03B9", A: -1, B: 1, F: nil},
}

var A_21 = []*snowballRuntime.Among{
	{Str: "\u03BA\u03B1\u03C4\u03C1\u03B1\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03BB\u03B1\u03B2\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B2\u03C1", A: 2, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B8\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B1\u03B3\u03BA\u03B1\u03C3", A: 8, B: 1, F: nil},
	{Str: "\u03BC\u03BF\u03C5\u03C3\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C1\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C6", A: 12, B: 1, F: nil},
	{Str: "\u03B1\u03BB\u03B9\u03C3\u03C6", A: 13, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03BC\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BB\u03BF\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B5\u03C7\u03BF\u03C3\u03BB\u03BF\u03B2", A: 17, B: 1, F: nil},
	{Str: "\u03C4\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA", A: 20, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C0\u03B1\u03BA", A: 20, B: 1, F: nil},
	{Str: "\u03C3\u03BF\u03BA", A: 20, B: 1, F: nil},
	{Str: "\u03C0\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B1\u03C1\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03B9\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BB\u03B9\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C0\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03BD", A: -1, B: 1, F: nil},
}

var A_22 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C4\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03C5\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C1\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C1\u03B9\u03C0\u03BF\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03BA\u03C1\u03C5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B9\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B3\u03BF\u03C5\u03BC\u03B5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03BD", A: -1, B: 1, F: nil},
}

var A_23 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C4\u03C3\u03B1\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C4\u03C3\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C4\u03C3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BA\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03B1\u03BA\u03B9\u03B1", A: 3, B: 1, F: nil},
	{Str: "\u03B1\u03BA\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03B1\u03BA\u03B9", A: 5, B: 1, F: nil},
	{Str: "\u03B9\u03C4\u03C3\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_24 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C8\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B9\u03C6\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03BB\u03BF", A: -1, B: 1, F: nil},
}

var A_25 = []*snowballRuntime.Among{
	{Str: "\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03B9\u03C7\u03BD", A: -1, B: 1, F: nil},
}

var A_26 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03B4\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B4\u03B9\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B4\u03B9\u03BF", A: -1, B: 1, F: nil},
}

var A_27 = []*snowballRuntime.Among{
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03C5\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C1\u03B1\u03B3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03B2\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B7\u03BD", A: -1, B: 1, F: nil},
}

var A_28 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03C3\u03BA\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BA\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BA\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C3\u03BA\u03BF", A: -1, B: 1, F: nil},
}

var A_29 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03B4\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B4\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_30 = []*snowballRuntime.Among{
	{Str: "\u03BC\u03C0\u03B1\u03BC\u03C0", A: -1, B: -1, F: nil},
	{Str: "\u03BA\u03C5\u03C1", A: -1, B: -1, F: nil},
	{Str: "\u03C0\u03B1\u03C4\u03B5\u03C1", A: -1, B: -1, F: nil},
	{Str: "\u03C0\u03B5\u03B8\u03B5\u03C1", A: -1, B: -1, F: nil},
	{Str: "\u03BD\u03C4\u03B1\u03BD\u03C4", A: -1, B: -1, F: nil},
	{Str: "\u03B3\u03B9\u03B1\u03B3\u03B9", A: -1, B: -1, F: nil},
	{Str: "\u03B8\u03B5\u03B9", A: -1, B: -1, F: nil},
	{Str: "\u03BF\u03BA", A: -1, B: -1, F: nil},
	{Str: "\u03BC\u03B1\u03BC", A: -1, B: -1, F: nil},
	{Str: "\u03BC\u03B1\u03BD", A: -1, B: -1, F: nil},
}

var A_31 = []*snowballRuntime.Among{
	{Str: "\u03B5\u03B4\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03B4\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_32 = []*snowballRuntime.Among{
	{Str: "\u03BA\u03C1\u03B1\u03C3\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B1\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B7\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BC\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B9\u03BB", A: -1, B: 1, F: nil},
}

var A_33 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03B4\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03B4\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_34 = []*snowballRuntime.Among{
	{Str: "\u03C3\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B9\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C1\u03B1\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03BB\u03B9\u03B1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C4\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BB\u03B5\u03BE", A: -1, B: 1, F: nil},
}

var A_35 = []*snowballRuntime.Among{
	{Str: "\u03B5\u03C9\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_36 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B4", A: 2, B: 1, F: nil},
	{Str: "\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BD", A: -1, B: 1, F: nil},
}

var A_37 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_38 = []*snowballRuntime.Among{
	{Str: "\u03B9\u03BA\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BA\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BA\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BA\u03BF", A: -1, B: 1, F: nil},
}

var A_39 = []*snowballRuntime.Among{
	{Str: "\u03BA\u03B1\u03BB\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BB\u03B9\u03B1\u03C4\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C4\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03C4\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03B5\u03C1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03B1\u03B3\u03B9\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B9\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03BA\u03B1\u03BD\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BE\u03C9\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C4\u03B1\u03B4", A: 13, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B1\u03B4", A: 13, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03C4\u03B9\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03BF\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03C9\u03C4\u03BF\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C5\u03BB\u03BF\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B7\u03B8", A: 21, B: 1, F: nil},
	{Str: "\u03BE\u03B9\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03BC\u03BF\u03C7\u03B1\u03BB", A: 25, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03BF\u03BC\u03B7\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03BF\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03C1\u03C9\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B1\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03BB\u03BB\u03B9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03C3\u03C4\u03B5\u03BB\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B9\u03BB\u03BF\u03BD", A: -1, B: 1, F: nil},
}

var A_40 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03C3\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B1\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B1\u03BC\u03B5", A: 3, B: 1, F: nil},
}

var A_41 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03BD\u03B1\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03BA\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03C3\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03B9\u03C7", A: 4, B: 1, F: nil},
	{Str: "\u03B2\u03BF\u03C5\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03BE\u03B5\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
}

var A_42 = []*snowballRuntime.Among{
	{Str: "\u03C4\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C3", A: -1, B: 1, F: nil},
}

var A_43 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03C3\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD\u03B5", A: 2, B: 1, F: nil},
	{Str: "\u03BF\u03BD\u03C4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BD\u03C4\u03B1\u03BD\u03B5", A: 4, B: 1, F: nil},
	{Str: "\u03BF\u03C4\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C4\u03B1\u03BD\u03B5", A: 6, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B1\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B1\u03BD\u03B5", A: 9, B: 1, F: nil},
}

var A_44 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BB\u03C5\u03B4\u03B1\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03B4\u03B1\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03BC\u03B7\u03BB\u03BF\u03B4\u03B1\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03BF\u03BA\u03BF\u03C0", A: 6, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B9\u03C4\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B5\u03C4\u03B5\u03C1", A: 10, B: 1, F: nil},
	{Str: "\u03B3\u03B5\u03C1", A: 10, B: 1, F: nil},
	{Str: "\u03BB\u03BF\u03C5\u03B8\u03B7\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03C1\u03BC\u03BF\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03B1\u03C1\u03B1\u03BA\u03B1\u03C4\u03C3", A: 15, B: 1, F: nil},
	{Str: "\u03B8\u03C5\u03C3", A: 15, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03C3", A: 15, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BB\u03B9\u03C3", A: 15, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C3\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BB\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B1\u03C1\u03BB\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03B5\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03C5\u03C1\u03B9\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BF\u03C5\u03BB\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B6\u03C9\u03BD\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03B9\u03BD\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03BD\u03C4\u03B1\u03C1\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03B9\u03BB\u03B1\u03C1\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03BF\u03C1\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03B1\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03C3\u03C4\u03B5\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03C6\u03C9\u03C4\u03BF\u03C3\u03C4\u03B5\u03C6", A: 34, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03C1\u03B7\u03C6", A: 29, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03B5\u03C1\u03B7\u03C6", A: 36, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BB\u03C5\u03BC\u03B7\u03C7", A: 38, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B7\u03C7", A: 38, B: 1, F: nil},
	{Str: "\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", A: 38, B: 1, F: nil},
	{Str: "\u03BC\u03B9\u03BA\u03C1\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", A: 41, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03B3\u03BB\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", A: 41, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C0\u03BD\u03BF\u03B2\u03B9\u03BF\u03BC\u03B7\u03C7", A: 41, B: 1, F: nil},
	{Str: "\u03BB\u03B9\u03C7", A: 38, B: 1, F: nil},
	{Str: "\u03C4\u03B1\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03C4\u03B1\u03B2", A: 46, B: 1, F: nil},
	{Str: "\u03C8\u03B7\u03BB\u03BF\u03C4\u03B1\u03B2", A: 46, B: 1, F: nil},
	{Str: "\u03BB\u03B9\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BB\u03B9\u03B2", A: 49, B: 1, F: nil},
	{Str: "\u03BE\u03B7\u03C1\u03BF\u03BA\u03BB\u03B9\u03B2", A: 50, B: 1, F: nil},
	{Str: "\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03BF\u03C1\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03BF\u03C1\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03B1\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03C4\u03C1\u03B1\u03B3", A: 55, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B1\u03B3", A: 55, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B9\u03B3\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03B1\u03C4\u03C3\u03B9\u03B3\u03B3", A: 58, B: 1, F: nil},
	{Str: "\u03B1\u03B8\u03B9\u03B3\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03C3\u03C4\u03B5\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03B7\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03C3\u03B9\u03B3", A: 52, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03BB\u03C0\u03BF\u03C5\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C9\u03B1\u03BC\u03B5\u03B8", A: 65, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03B8", A: 65, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03B9\u03B8", A: 67, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03C3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03C1\u03B1\u03C7\u03C5\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B5\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03BB\u03B5\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B9\u03BA", A: 73, B: 1, F: nil},
	{Str: "\u03B2\u03BF\u03C5\u03BB\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03C0\u03BB", A: 76, B: 1, F: nil},
	{Str: "\u03C8\u03C5\u03C7\u03BF\u03C0\u03BB", A: 76, B: 1, F: nil},
	{Str: "\u03BB\u03B1\u03BF\u03C0\u03BB", A: 76, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B3\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03B8\u03C5\u03B3\u03B1\u03BB", A: 81, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C4\u03B1\u03B3\u03B1\u03BB", A: 81, B: 1, F: nil},
	{Str: "\u03BF\u03BB\u03BF\u03B3\u03B1\u03BB", A: 81, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03C3\u03C4\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03C1\u03C4\u03BF\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03C1\u03B1\u03B4\u03BF\u03C5\u03BC", A: 88, B: 1, F: nil},
	{Str: "\u03B2\u03C1\u03B1\u03C7\u03BC", A: 88, B: 1, F: nil},
	{Str: "\u03BF\u03BB\u03B9\u03B3\u03BF\u03B4\u03B1\u03BC", A: 88, B: 1, F: nil},
	{Str: "\u03BC\u03BF\u03C5\u03C3\u03BF\u03C5\u03BB\u03BC", A: 88, B: 1, F: nil},
	{Str: "\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B5\u03C1\u03B9\u03BA\u03B1\u03BD", A: 93, B: 1, F: nil},
}

var A_45 = []*snowballRuntime.Among{
	{Str: "\u03B7\u03C3\u03B5\u03C4\u03B5", A: -1, B: 1, F: nil},
}

var A_46 = []*snowballRuntime.Among{
	{Str: "\u03C0\u03C5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03C9\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B9\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03BF\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B5\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03B5\u03C1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C5\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C1\u03B1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03B1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03B1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03B9\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BA\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C1\u03BF\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03C6\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03BF\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03C1\u03BF\u03BD", A: -1, B: 1, F: nil},
}

var A_47 = []*snowballRuntime.Among{
	{Str: "\u03C3\u03B5\u03C1\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B8\u03B1\u03C1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03C4\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B2\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B2\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03C0\u03BF\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03C1\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B9\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B4", A: 12, B: 1, F: nil},
	{Str: "\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B8", A: 14, B: 1, F: nil},
	{Str: "\u03C3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03BF\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B2\u03B1\u03C1\u03BF\u03BD", A: -1, B: 1, F: nil},
}

var A_48 = []*snowballRuntime.Among{
	{Str: "\u03C9\u03BD\u03C4\u03B1\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03BD\u03C4\u03B1\u03C3", A: -1, B: 1, F: nil},
}

var A_49 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03BC\u03B1\u03C3\u03C4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BC\u03B1\u03C3\u03C4\u03B5", A: 0, B: 1, F: nil},
}

var A_50 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03BA\u03B1\u03C4\u03B1\u03C0", A: 1, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BC\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03C5\u03BC\u03C0", A: 3, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B5\u03C4\u03B1\u03BC\u03C6", A: -1, B: 1, F: nil},
}

var A_51 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B9\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03BB", A: 3, B: 1, F: nil},
	{Str: "\u03B5\u03BA\u03C4\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BE", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03BF", A: -1, B: 1, F: nil},
}

var A_52 = []*snowballRuntime.Among{
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B5", A: -1, B: 1, F: nil},
}

var A_53 = []*snowballRuntime.Among{
	{Str: "\u03C3\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03BD\u03B1\u03C1\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B9\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03BF\u03C5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BA\u03C9\u03BB", A: -1, B: 1, F: nil},
}

var A_54 = []*snowballRuntime.Among{
	{Str: "\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03BF\u03C3\u03B8", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C1\u03B1\u03BA\u03B1\u03C4\u03B1\u03B8", A: 0, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03B1\u03B8", A: 0, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03B8", A: 0, B: 1, F: nil},
}

var A_55 = []*snowballRuntime.Among{
	{Str: "\u03B7\u03BA\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B5", A: -1, B: 1, F: nil},
}

var A_56 = []*snowballRuntime.Among{
	{Str: "\u03B2\u03BB\u03B5\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03B4\u03B1\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03C9\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03C5\u03BC\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03BD\u03C4\u03B1\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B1\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B1\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B7\u03B3", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C1\u03C5\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03BD\u03C4\u03B9\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03BB\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03BC", A: -1, B: 1, F: nil},
}

var A_57 = []*snowballRuntime.Among{
	{Str: "\u03B5\u03BA\u03BB\u03B9\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B1\u03C1\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03B5\u03BD\u03B4\u03B9\u03B1\u03C6\u03B5\u03C1", A: 1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03B8\u03B1\u03C1\u03B5\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B5\u03C5\u03C4\u03B5\u03C1\u03B5\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B5\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03B1\u03BC\u03C0\u03B9\u03B4", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BB\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03C3\u03B1\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B5\u03C3\u03C0\u03BF\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B9\u03B8", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03B1\u03C1\u03BC\u03B1\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03B7\u03BA", A: -1, B: 1, F: nil},
	{Str: "\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC", A: 21, B: 1, F: nil},
	{Str: "\u03B2\u03C1\u03BF\u03BC", A: 21, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03BF\u03C4\u03B5\u03B9\u03BD", A: -1, B: 1, F: nil},
}

var A_58 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03C3\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C3\u03B5", A: -1, B: 1, F: nil},
}

var A_59 = []*snowballRuntime.Among{
	{Str: "\u03C8\u03BF\u03C6", A: -1, B: -1, F: nil},
	{Str: "\u03BD\u03B1\u03C5\u03BB\u03BF\u03C7", A: -1, B: -1, F: nil},
}

var A_60 = []*snowballRuntime.Among{
	{Str: "\u03C1\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C6\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C7\u03BF\u03C1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03BF\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B5\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03BB\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03BC\u03B7\u03BD", A: -1, B: 1, F: nil},
}

var A_61 = []*snowballRuntime.Among{
	{Str: "\u03C0", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03C5\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03C1\u03C4\u03B9\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03B5\u03B9\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BC\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03BF\u03C3\u03C9\u03C0\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C3\u03B9\u03B4\u03B7\u03C1\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03B4\u03C1\u03BF\u03C3\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03BD\u03B5\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03BA\u03C1\u03BF\u03BA\u03B1\u03BB\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03BF\u03BB\u03BF\u03C0", A: 0, B: 1, F: nil},
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C4\u03C1", A: 12, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C1", A: 12, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03C0\u03B1\u03C1", A: 12, B: 1, F: nil},
	{Str: "\u03C7\u03B1\u03C1", A: 12, B: 1, F: nil},
	{Str: "\u03B1\u03C7\u03B1\u03C1", A: 16, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03B5\u03C1", A: 12, B: 1, F: nil},
	{Str: "\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BD\u03C5\u03C3\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03B1\u03B2\u03B1\u03C3\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03C0\u03C1\u03BF\u03C3\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03B1\u03B9\u03BC\u03BF\u03C3\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03B4\u03B9\u03B1\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03B9\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03C3\u03C5\u03BD\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03C5\u03C0\u03BF\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BF\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03BF\u03BC\u03BF\u03C4", A: 19, B: 1, F: nil},
	{Str: "\u03BD\u03BF\u03BC\u03BF\u03C4", A: 29, B: 1, F: nil},
	{Str: "\u03BD\u03B1\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03BF\u03BB\u03C5\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03BE\u03B5\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B4\u03B7\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03BC\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B1\u03BB\u03BB\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B1\u03BB", A: 38, B: 1, F: nil},
	{Str: "\u03BC", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BB\u03B1\u03BC", A: 40, B: 1, F: nil},
	{Str: "\u03B5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03B5\u03C1\u03B2\u03B5\u03BD", A: 42, B: 1, F: nil},
}

var A_62 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03B3\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B5", A: -1, B: 1, F: nil},
}

var A_63 = []*snowballRuntime.Among{
	{Str: "\u03B7\u03C3\u03BF\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B5", A: -1, B: 1, F: nil},
}

var A_64 = []*snowballRuntime.Among{
	{Str: "\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C0\u03C4\u03B1\u03BD", A: 0, B: 1, F: nil},
	{Str: "\u03B4\u03C9\u03B4\u03B5\u03BA\u03B1\u03BD", A: 0, B: 1, F: nil},
	{Str: "\u03C7\u03B5\u03C1\u03C3\u03BF\u03BD", A: 0, B: 1, F: nil},
	{Str: "\u03BC\u03B5\u03B3\u03B1\u03BB\u03BF\u03BD", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03C1\u03B7\u03BC\u03BF\u03BD", A: 0, B: 1, F: nil},
}

var A_65 = []*snowballRuntime.Among{
	{Str: "\u03B7\u03C3\u03C4\u03B5", A: -1, B: 1, F: nil},
}

var A_66 = []*snowballRuntime.Among{
	{Str: "\u03C7\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B4\u03C5\u03C3\u03C7\u03C1", A: 0, B: 1, F: nil},
	{Str: "\u03B5\u03C5\u03C7\u03C1", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03C7\u03C1", A: 0, B: 1, F: nil},
	{Str: "\u03BA\u03BF\u03B9\u03BD\u03BF\u03C7\u03C1", A: 0, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03BB\u03B9\u03BC\u03C8", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03B2", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03B2", A: 6, B: 1, F: nil},
	{Str: "\u03B1\u03C0\u03BB", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B5\u03B9\u03BC\u03BD", A: -1, B: 1, F: nil},
}

var A_67 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03BD\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03BF\u03C5\u03BD\u03B5", A: 0, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03BF\u03C5\u03BD\u03B5", A: 0, B: 1, F: nil},
}

var A_68 = []*snowballRuntime.Among{
	{Str: "\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C4\u03C1\u03B1\u03B2\u03BF\u03BC\u03BF\u03C5\u03C4\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BA\u03B1\u03BA\u03BF\u03BC\u03BF\u03C5\u03C4\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C3\u03C0\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03BE\u03C9\u03BD", A: 4, B: 1, F: nil},
}

var A_69 = []*snowballRuntime.Among{
	{Str: "\u03BF\u03C5\u03BC\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03BF\u03C5\u03BC\u03B5", A: 0, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03BF\u03C5\u03BC\u03B5", A: 0, B: 1, F: nil},
}

var A_70 = []*snowballRuntime.Among{
	{Str: "\u03B1\u03C3\u03BF\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C0\u03B1\u03C1\u03B1\u03C3\u03BF\u03C5\u03C3", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03BB\u03BB\u03BF\u03C3\u03BF\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C6", A: -1, B: 1, F: nil},
	{Str: "\u03C7", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03B6", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03C1\u03B9\u03BF\u03C0\u03BB", A: -1, B: 1, F: nil},
}

var A_71 = []*snowballRuntime.Among{
	{Str: "\u03BC\u03B1\u03C4\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03C4\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03BC\u03B1\u03C4\u03C9\u03BD", A: -1, B: 1, F: nil},
}

var A_72 = []*snowballRuntime.Among{
	{Str: "\u03C5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C3", A: 0, B: 1, F: nil},
	{Str: "\u03B1\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B5\u03C3", A: 3, B: 1, F: nil},
	{Str: "\u03B7\u03B4\u03B5\u03C3", A: 3, B: 1, F: nil},
	{Str: "\u03B7\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03B9\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B5\u03B9\u03C3", A: 7, B: 1, F: nil},
	{Str: "\u03BF\u03C3", A: -1, B: 1, F: nil},
	{Str: "\u03C5", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5", A: 10, B: 1, F: nil},
	{Str: "\u03C9", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03C9", A: 12, B: 1, F: nil},
	{Str: "\u03B1\u03C9", A: 12, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03C9", A: 12, B: 1, F: nil},
	{Str: "\u03B1", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C5\u03BC\u03B1", A: 16, B: 1, F: nil},
	{Str: "\u03BF\u03C3\u03BF\u03C5\u03BD\u03B1", A: 16, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C3\u03BF\u03C5\u03BD\u03B1", A: 18, B: 1, F: nil},
	{Str: "\u03BF\u03BC\u03BF\u03C5\u03BD\u03B1", A: 16, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BC\u03BF\u03C5\u03BD\u03B1", A: 20, B: 1, F: nil},
	{Str: "\u03B5", A: -1, B: 1, F: nil},
	{Str: "\u03B9\u03B5\u03C3\u03B1\u03C3\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03BF\u03C3\u03B1\u03C3\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C3\u03B1\u03C3\u03C4\u03B5", A: 24, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BC\u03B1\u03C3\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C5\u03BC\u03B1\u03C3\u03C4\u03B5", A: 26, B: 1, F: nil},
	{Str: "\u03B9\u03B5\u03BC\u03B1\u03C3\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C3\u03B1\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B1\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B1\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B1\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B1\u03C4\u03B5", A: 32, B: 1, F: nil},
	{Str: "\u03B5\u03B9\u03C4\u03B5", A: 22, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B5\u03B9\u03C4\u03B5", A: 34, B: 1, F: nil},
	{Str: "\u03B7", A: -1, B: 1, F: nil},
	{Str: "\u03B9", A: -1, B: 1, F: nil},
	{Str: "\u03B1\u03C3\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B9\u03B5\u03C3\u03B1\u03B9", A: 39, B: 1, F: nil},
	{Str: "\u03B1\u03C4\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B5\u03C4\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B9\u03B5\u03C4\u03B1\u03B9", A: 42, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BD\u03C4\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03B9", A: 44, B: 1, F: nil},
	{Str: "\u03BF\u03BD\u03C4\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BC\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B1\u03BC\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B9\u03B5\u03BC\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03BF\u03BC\u03B1\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B5\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B5\u03B9", A: 51, B: 1, F: nil},
	{Str: "\u03B1\u03B5\u03B9", A: 51, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B5\u03B9", A: 51, B: 1, F: nil},
	{Str: "\u03BF\u03B9", A: 37, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03BF\u03C5\u03BD", A: 56, B: 1, F: nil},
	{Str: "\u03BF\u03C3\u03BF\u03C5\u03BD", A: 56, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C3\u03BF\u03C5\u03BD", A: 58, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03BF\u03C5\u03BD", A: 56, B: 1, F: nil},
	{Str: "\u03BF\u03BC\u03BF\u03C5\u03BD", A: 56, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BC\u03BF\u03C5\u03BD", A: 61, B: 1, F: nil},
	{Str: "\u03C9\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03B7\u03B4\u03C9\u03BD", A: 63, B: 1, F: nil},
	{Str: "\u03B1\u03BD", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03C3\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03BF\u03BD\u03C4\u03BF\u03C5\u03C3\u03B1\u03BD", A: 66, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BD\u03C4\u03BF\u03C5\u03C3\u03B1\u03BD", A: 67, B: 1, F: nil},
	{Str: "\u03B7\u03C3\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03BF\u03C3\u03B1\u03C3\u03C4\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C3\u03B1\u03C3\u03C4\u03B1\u03BD", A: 70, B: 1, F: nil},
	{Str: "\u03BF\u03BC\u03B1\u03C3\u03C4\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BC\u03B1\u03C3\u03C4\u03B1\u03BD", A: 72, B: 1, F: nil},
	{Str: "\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C5\u03BD\u03C4\u03B1\u03BD", A: 74, B: 1, F: nil},
	{Str: "\u03BF\u03BD\u03C4\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03BD\u03C4\u03B1\u03BD", A: 76, B: 1, F: nil},
	{Str: "\u03BF\u03C4\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B9\u03BF\u03C4\u03B1\u03BD", A: 78, B: 1, F: nil},
	{Str: "\u03B1\u03B3\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B7\u03BA\u03B1\u03BD", A: 65, B: 1, F: nil},
	{Str: "\u03B7\u03B8\u03B7\u03BA\u03B1\u03BD", A: 81, B: 1, F: nil},
	{Str: "\u03BF", A: -1, B: 1, F: nil},
}

var A_73 = []*snowballRuntime.Among{
	{Str: "\u03B5\u03C3\u03C4\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C4\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03C4\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C4\u03B5\u03C1", A: -1, B: 1, F: nil},
	{Str: "\u03B5\u03C3\u03C4\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C5\u03C4\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03C9\u03C4\u03B1\u03C4", A: -1, B: 1, F: nil},
	{Str: "\u03BF\u03C4\u03B1\u03C4", A: -1, B: 1, F: nil},
}

var G_v = []byte{81, 65, 16, 1}

var G_v2 = []byte{81, 65, 0, 1}

type Context struct {
	b_test1 bool
}

func r_has_min_length(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	if !(snowballRuntime.RuneCountInString(env.Current()) >= 3) {
		return false
	}
	return true
}

func r_tolower(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
replab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for range [2]struct{}{} {
			env.Ket = env.Cursor
			among_var = env.FindAmongB(A_0, context)
			if among_var == 0 {
				break lab1
			}
			env.Bra = env.Cursor
			if among_var == 1 {
				if !env.SliceFrom("\u03B1") {
					return false
				}
			} else if among_var == 2 {
				if !env.SliceFrom("\u03B2") {
					return false
				}
			} else if among_var == 3 {
				if !env.SliceFrom("\u03B3") {
					return false
				}
			} else if among_var == 4 {
				if !env.SliceFrom("\u03B4") {
					return false
				}
			} else if among_var == 5 {
				if !env.SliceFrom("\u03B5") {
					return false
				}
			} else if among_var == 6 {
				if !env.SliceFrom("\u03B6") {
					return false
				}
			} else if among_var == 7 {
				if !env.SliceFrom("\u03B7") {
					return false
				}
			} else if among_var == 8 {
				if !env.SliceFrom("\u03B8") {
					return false
				}
			} else if among_var == 9 {
				if !env.SliceFrom("\u03B9") {
					return false
				}
			} else if among_var == 10 {
				if !env.SliceFrom("\u03BA") {
					return false
				}
			} else if among_var == 11 {
				if !env.SliceFrom("\u03BB") {
					return false
				}
			} else if among_var == 12 {
				if !env.SliceFrom("\u03BC") {
					return false
				}
			} else if among_var == 13 {
				if !env.SliceFrom("\u03BD") {
					return false
				}
			} else if among_var == 14 {
				if !env.SliceFrom("\u03BE") {
					return false
				}
			} else if among_var == 15 {
				if !env.SliceFrom("\u03BF") {
					return false
				}
			} else if among_var == 16 {
				if !env.SliceFrom("\u03C0") {
					return false
				}
			} else if among_var == 17 {
				if !env.SliceFrom("\u03C1") {
					return false
				}
			} else if among_var == 18 {
				if !env.SliceFrom("\u03C3") {
					return false
				}
			} else if among_var == 19 {
				if !env.SliceFrom("\u03C4") {
					return false
				}
			} else if among_var == 20 {
				if !env.SliceFrom("\u03C5") {
					return false
				}
			} else if among_var == 21 {
				if !env.SliceFrom("\u03C6") {
					return false
				}
			} else if among_var == 22 {
				if !env.SliceFrom("\u03C7") {
					return false
				}
			} else if among_var == 23 {
				if !env.SliceFrom("\u03C8") {
					return false
				}
			} else if among_var == 24 {
				if !env.SliceFrom("\u03C9") {
					return false
				}
			} else if among_var == 25 {
				if env.Cursor <= env.LimitBackward {
					break lab1
				}
				env.PrevChar()
			}
			continue replab0
		}
		env.Cursor = env.Limit - v_1
		break replab0
	}
	return true
}

func r_step1(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	among_var = env.FindAmongB(A_1, context)
	if among_var == 0 {
		return false
	}
	env.Bra = env.Cursor
	if among_var == 1 {
		if !env.SliceFrom("\u03C6\u03B1") {
			return false
		}
	} else if among_var == 2 {
		if !env.SliceFrom("\u03C3\u03BA\u03B1") {
			return false
		}
	} else if among_var == 3 {
		if !env.SliceFrom("\u03BF\u03BB\u03BF") {
			return false
		}
	} else if among_var == 4 {
		if !env.SliceFrom("\u03C3\u03BF") {
			return false
		}
	} else if among_var == 5 {
		if !env.SliceFrom("\u03C4\u03B1\u03C4\u03BF") {
			return false
		}
	} else if among_var == 6 {
		if !env.SliceFrom("\u03BA\u03C1\u03B5") {
			return false
		}
	} else if among_var == 7 {
		if !env.SliceFrom("\u03C0\u03B5\u03C1") {
			return false
		}
	} else if among_var == 8 {
		if !env.SliceFrom("\u03C4\u03B5\u03C1") {
			return false
		}
	} else if among_var == 9 {
		if !env.SliceFrom("\u03C6\u03C9") {
			return false
		}
	} else if among_var == 10 {
		if !env.SliceFrom("\u03BA\u03B1\u03B8\u03B5\u03C3\u03C4") {
			return false
		}
	} else if among_var == 11 {
		if !env.SliceFrom("\u03B3\u03B5\u03B3\u03BF\u03BD") {
			return false
		}
	}
	context.b_test1 = false
	return true
}

func r_steps1(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_4, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_2, context) == 0 {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B9") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_3, context) == 0 {
			return false
		}
		if env.Cursor > env.LimitBackward {
			return false
		}
		if !env.SliceFrom("\u03B9\u03B6") {
			return false
		}
		break lab0
	}
	return true
}

func r_steps2(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_6, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_5, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03C9\u03BD") {
		return false
	}
	return true
}

func r_steps3(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_9, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			if !env.EqSB("\u03B9\u03C3\u03B1") {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B9\u03C3") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_7, context) == 0 {
				break lab2
			}
			if env.Cursor > env.LimitBackward {
				break lab2
			}
			if !env.SliceFrom("\u03B9") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_8, context) == 0 {
			return false
		}
		if env.Cursor > env.LimitBackward {
			return false
		}
		if !env.SliceFrom("\u03B9\u03C3") {
			return false
		}
		break lab0
	}
	return true
}

func r_steps4(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_11, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_10, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B9") {
		return false
	}
	return true
}

func r_steps5(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_14, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_12, context) == 0 {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B9") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_13, context) == 0 {
			return false
		}
		if env.Cursor > env.LimitBackward {
			return false
		}
		if !env.SliceFrom("\u03B9\u03C3\u03C4") {
			return false
		}
		break lab0
	}
	return true
}

func r_steps6(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var among_var int32
	env.Ket = env.Cursor
	if env.FindAmongB(A_18, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_15, context) == 0 {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B9\u03C3\u03BC") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_16, context) == 0 {
				break lab2
			}
			if env.Cursor > env.LimitBackward {
				break lab2
			}
			if !env.SliceFrom("\u03B9") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		among_var = env.FindAmongB(A_17, context)
		if among_var == 0 {
			return false
		}
		env.Bra = env.Cursor
		if among_var == 1 {
			if !env.SliceFrom("\u03B1\u03B3\u03BD\u03C9\u03C3\u03C4") {
				return false
			}
		} else if among_var == 2 {
			if !env.SliceFrom("\u03B1\u03C4\u03BF\u03BC") {
				return false
			}
		} else if among_var == 3 {
			if !env.SliceFrom("\u03B3\u03BD\u03C9\u03C3\u03C4") {
				return false
			}
		} else if among_var == 4 {
			if !env.SliceFrom("\u03B5\u03B8\u03BD") {
				return false
			}
		} else if among_var == 5 {
			if !env.SliceFrom("\u03B5\u03BA\u03BB\u03B5\u03BA\u03C4") {
				return false
			}
		} else if among_var == 6 {
			if !env.SliceFrom("\u03C3\u03BA\u03B5\u03C0\u03C4") {
				return false
			}
		} else if among_var == 7 {
			if !env.SliceFrom("\u03C4\u03BF\u03C0") {
				return false
			}
		} else if among_var == 8 {
			if !env.SliceFrom("\u03B1\u03BB\u03B5\u03BE\u03B1\u03BD\u03B4\u03C1") {
				return false
			}
		} else if among_var == 9 {
			if !env.SliceFrom("\u03B2\u03C5\u03B6\u03B1\u03BD\u03C4") {
				return false
			}
		} else if among_var == 10 {
			if !env.SliceFrom("\u03B8\u03B5\u03B1\u03C4\u03C1") {
				return false
			}
		}
		break lab0
	}
	return true
}

func r_steps7(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_20, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_19, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B1\u03C1\u03B1\u03BA") {
		return false
	}
	return true
}

func r_steps8(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_23, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_21, context) == 0 {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B1\u03BA") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_22, context) == 0 {
				break lab2
			}
			if env.Cursor > env.LimitBackward {
				break lab2
			}
			if !env.SliceFrom("\u03B9\u03C4\u03C3") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if !env.EqSB("\u03BA\u03BF\u03C1") {
			return false
		}
		if !env.SliceFrom("\u03B9\u03C4\u03C3") {
			return false
		}
		break lab0
	}
	return true
}

func r_steps9(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_26, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_24, context) == 0 {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03B9\u03B4") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_25, context) == 0 {
			return false
		}
		if !env.SliceFrom("\u03B9\u03B4") {
			return false
		}
		break lab0
	}
	return true
}

func r_steps10(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_28, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_27, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B9\u03C3\u03BA") {
		return false
	}
	return true
}

func r_step2a(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_29, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_30, context) == 0 {
			break lab0
		}
		env.Bra = env.Cursor
		return false
	}
	env.Cursor = env.Limit - v_1
	{
		var c = env.Cursor
		bra, ket := env.Cursor, env.Cursor
		env.Insert(bra, ket, "\u03B1\u03B4")
		env.Cursor = c
	}
	return true
}

func r_step2b(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_31, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_32, context) == 0 {
		return false
	}
	if !env.SliceFrom("\u03B5\u03B4") {
		return false
	}
	return true
}

func r_step2c(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_33, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_34, context) == 0 {
		return false
	}
	if !env.SliceFrom("\u03BF\u03C5\u03B4") {
		return false
	}
	return true
}

func r_step2d(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_35, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_36, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B5") {
		return false
	}
	return true
}

func r_step3(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_37, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if !env.InGroupingB(G_v, 945, 969) {
		return false
	}
	if !env.SliceFrom("\u03B9") {
		return false
	}
	return true
}

func r_step4(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_38, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if !env.InGroupingB(G_v, 945, 969) {
				break lab1
			}
			if !env.SliceFrom("\u03B9\u03BA") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		break lab0
	}
	env.Bra = env.Cursor
	if env.FindAmongB(A_39, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B9\u03BA") {
		return false
	}
	return true
}

func r_step5a(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		if !env.EqSB("\u03B1\u03B3\u03B1\u03BC\u03B5") {
			break lab0
		}
		if env.Cursor > env.LimitBackward {
			break lab0
		}
		if !env.SliceFrom("\u03B1\u03B3\u03B1\u03BC") {
			return false
		}
		break lab0
	}
	env.Cursor = env.Limit - v_1
	var v_2 = env.Limit - env.Cursor
lab1:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_40, context) == 0 {
			break lab1
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		context.b_test1 = false
		break lab1
	}
	env.Cursor = env.Limit - v_2
	env.Ket = env.Cursor
	if !env.EqSB("\u03B1\u03BC\u03B5") {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_41, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B1\u03BC") {
		return false
	}
	return true
}

func r_step5b(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_43, context) == 0 {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		context.b_test1 = false
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_42, context) == 0 {
			break lab0
		}
		if env.Cursor > env.LimitBackward {
			break lab0
		}
		if !env.SliceFrom("\u03B1\u03B3\u03B1\u03BD") {
			return false
		}
		break lab0
	}
	env.Cursor = env.Limit - v_1
	env.Ket = env.Cursor
	if !env.EqSB("\u03B1\u03BD\u03B5") {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab1:
	for {
		var v_2 = env.Limit - env.Cursor
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if !env.InGroupingB(G_v2, 945, 969) {
				break lab2
			}
			if !env.SliceFrom("\u03B1\u03BD") {
				return false
			}
			break lab1
		}
		env.Cursor = env.Limit - v_2
		env.Ket = env.Cursor
		break lab1
	}
	env.Bra = env.Cursor
	if env.FindAmongB(A_44, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B1\u03BD") {
		return false
	}
	return true
}

func r_step5c(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_45, context) == 0 {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		context.b_test1 = false
		break lab0
	}
	env.Cursor = env.Limit - v_1
	env.Ket = env.Cursor
	if !env.EqSB("\u03B5\u03C4\u03B5") {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab1:
	for {
		var v_2 = env.Limit - env.Cursor
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if !env.InGroupingB(G_v2, 945, 969) {
				break lab2
			}
			if !env.SliceFrom("\u03B5\u03C4") {
				return false
			}
			break lab1
		}
		env.Cursor = env.Limit - v_2
	lab3:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_46, context) == 0 {
				break lab3
			}
			if !env.SliceFrom("\u03B5\u03C4") {
				return false
			}
			break lab1
		}
		env.Cursor = env.Limit - v_2
		env.Ket = env.Cursor
		break lab1
	}
	env.Bra = env.Cursor
	if env.FindAmongB(A_47, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B5\u03C4") {
		return false
	}
	return true
}

func r_step5d(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_48, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if !env.EqSB("\u03B1\u03C1\u03C7") {
				break lab1
			}
			if env.Cursor > env.LimitBackward {
				break lab1
			}
			if !env.SliceFrom("\u03BF\u03BD\u03C4") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if !env.EqSB("\u03BA\u03C1\u03B5") {
			return false
		}
		if !env.SliceFrom("\u03C9\u03BD\u03C4") {
			return false
		}
		break lab0
	}
	return true
}

func r_step5e(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_49, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if !env.EqSB("\u03BF\u03BD") {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03BF\u03BC\u03B1\u03C3\u03C4") {
		return false
	}
	return true
}

func r_step5f(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if !env.EqSB("\u03B9\u03B5\u03C3\u03C4\u03B5") {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		context.b_test1 = false
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_50, context) == 0 {
			break lab0
		}
		if env.Cursor > env.LimitBackward {
			break lab0
		}
		if !env.SliceFrom("\u03B9\u03B5\u03C3\u03C4") {
			return false
		}
		break lab0
	}
	env.Cursor = env.Limit - v_1
	env.Ket = env.Cursor
	if !env.EqSB("\u03B5\u03C3\u03C4\u03B5") {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_51, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B9\u03B5\u03C3\u03C4") {
		return false
	}
	return true
}

func r_step5g(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_52, context) == 0 {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceDel() {
			return false
		}
		context.b_test1 = false
		break lab0
	}
	env.Cursor = env.Limit - v_1
	env.Ket = env.Cursor
	if env.FindAmongB(A_55, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab1:
	for {
		var v_2 = env.Limit - env.Cursor
	lab2:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_53, context) == 0 {
				break lab2
			}
			if !env.SliceFrom("\u03B7\u03BA") {
				return false
			}
			break lab1
		}
		env.Cursor = env.Limit - v_2
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_54, context) == 0 {
			return false
		}
		if env.Cursor > env.LimitBackward {
			return false
		}
		if !env.SliceFrom("\u03B7\u03BA") {
			return false
		}
		break lab1
	}
	return true
}

func r_step5h(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_58, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_56, context) == 0 {
				break lab1
			}
			if !env.SliceFrom("\u03BF\u03C5\u03C3") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		env.Ket = env.Cursor
		env.Bra = env.Cursor
		if env.FindAmongB(A_57, context) == 0 {
			return false
		}
		if env.Cursor > env.LimitBackward {
			return false
		}
		if !env.SliceFrom("\u03BF\u03C5\u03C3") {
			return false
		}
		break lab0
	}
	return true
}

func r_step5i(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_62, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
lab0:
	for {
		var v_1 = env.Limit - env.Cursor
	lab1:
		for {
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if !env.EqSB("\u03BA\u03BF\u03BB\u03BB") {
				break lab1
			}
			if !env.SliceFrom("\u03B1\u03B3") {
				return false
			}
			break lab0
		}
		env.Cursor = env.Limit - v_1
		var v_2 = env.Limit - env.Cursor
	lab2:
		for {
			env.Ket = env.Cursor
			if env.FindAmongB(A_59, context) == 0 {
				break lab2
			}
			env.Bra = env.Cursor
			return false
		}
		env.Cursor = env.Limit - v_2
	lab3:
		for {
			var v_3 = env.Limit - env.Cursor
		lab4:
			for {
				env.Ket = env.Cursor
				env.Bra = env.Cursor
				if env.FindAmongB(A_60, context) == 0 {
					break lab4
				}
				if !env.SliceFrom("\u03B1\u03B3") {
					return false
				}
				break lab3
			}
			env.Cursor = env.Limit - v_3
			env.Ket = env.Cursor
			env.Bra = env.Cursor
			if env.FindAmongB(A_61, context) == 0 {
				return false
			}
			if env.Cursor > env.LimitBackward {
				return false
			}
			if !env.SliceFrom("\u03B1\u03B3") {
				return false
			}
			break lab3
		}
		break lab0
	}
	return true
}

func r_step5j(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_63, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_64, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B7\u03C3") {
		return false
	}
	return true
}

func r_step5k(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_65, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_66, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03B7\u03C3\u03C4") {
		return false
	}
	return true
}

func r_step5l(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_67, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_68, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03BF\u03C5\u03BD") {
		return false
	}
	return true
}

func r_step5m(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_69, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	context.b_test1 = false
	env.Ket = env.Cursor
	env.Bra = env.Cursor
	if env.FindAmongB(A_70, context) == 0 {
		return false
	}
	if env.Cursor > env.LimitBackward {
		return false
	}
	if !env.SliceFrom("\u03BF\u03C5\u03BC") {
		return false
	}
	return true
}

func r_step6(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	var v_1 = env.Limit - env.Cursor
lab0:
	for {
		env.Ket = env.Cursor
		if env.FindAmongB(A_71, context) == 0 {
			break lab0
		}
		env.Bra = env.Cursor
		if !env.SliceFrom("\u03BC\u03B1") {
			return false
		}
		break lab0
	}
	env.Cursor = env.Limit - v_1
	if !context.b_test1 {
		return false
	}
	env.Ket = env.Cursor
	if env.FindAmongB(A_72, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func r_step7(env *snowballRuntime.Env, ctx interface{}) bool {
	context := ctx.(*Context)
	_ = context
	env.Ket = env.Cursor
	if env.FindAmongB(A_73, context) == 0 {
		return false
	}
	env.Bra = env.Cursor
	if !env.SliceDel() {
		return false
	}
	return true
}

func Stem(env *snowballRuntime.Env) bool {
	var context = &Context{
		b_test1: false,
	}
	_ = context
	env.LimitBackward = env.Cursor
	env.Cursor = env.Limit
	var v_1 = env.Limit - env.Cursor
	r_tolower(env, context)
	env.Cursor = env.Limit - v_1
	if !r_has_min_length(env, context) {
		return false
	}
	context.b_test1 = true
	var v_2 = env.Limit - env.Cursor
	r_step1(env, context)
	env.Cursor = env.Limit - v_2
	var v_3 = env.Limit - env.Cursor
	r_steps1(env, context)
	env.Cursor = env.Limit - v_3
	var v_4 = env.Limit - env.Cursor
	r_steps2(env, context)
	env.Cursor = env.Limit - v_4
	var v_5 = env.Limit - env.Cursor
	r_steps3(env, context)
	env.Cursor = env.Limit - v_5
	var v_6 = env.Limit - env.Cursor
	r_steps4(env, context)
	env.Cursor = env.Limit - v_6
	var v_7 = env.Limit - env.Cursor
	r_steps5(env, context)
	env.Cursor = env.Limit - v_7
	var v_8 = env.Limit - env.Cursor
	r_steps6(env, context)
	env.Cursor = env.Limit - v_8
	var v_9 = env.Limit - env.Cursor
	r_steps7(env, context)
	env.Cursor = env.Limit - v_9
	var v_10 = env.Limit - env.Cursor
	r_steps8(env, context)
	env.Cursor = env.Limit - v_10
	var v_11 = env.Limit - env.Cursor
	r_steps9(env, context)
	env.Cursor = env.Limit - v_11
	var v_12 = env.Limit - env.Cursor
	r_steps10(env, context)
	env.Cursor = env.Limit - v_12
	var v_13 = env.Limit - env.Cursor
	r_step2a(env, context)
	env.Cursor = env.Limit - v_13
	var v_14 = env.Limit - env.Cursor
	r_step2b(env, context)
	env.Cursor = env.Limit - v_14
	var v_15 = env.Limit - env.Cursor
	r_step2c(env, context)
	env.Cursor = env.Limit - v_15
	var v_16 = env.Limit - env.Cursor
	r_step2d(env, context)
	env.Cursor = env.Limit - v_16
	var v_17 = env.Limit - env.Cursor
	r_step3(env, context)
	env.Cursor = env.Limit - v_17
	var v_18 = env.Limit - env.Cursor
	r_step4(env, context)
	env.Cursor = env.Limit - v_18
	var v_19 = env.Limit - env.Cursor
	r_step5a(env, context)
	env.Cursor = env.Limit - v_19
	var v_20 = env.Limit - env.Cursor
	r_step5b(env, context)
	env.Cursor = env.Limit - v_20
	var v_21 = env.Limit - env.Cursor
	r_step5c(env, context)
	env.Cursor = env.Limit - v_21
	var v_22 = env.Limit - env.Cursor
	r_step5d(env, context)
	env.Cursor = env.Limit - v_22
	var v_23 = env.Limit - env.Cursor
	r_step5e(env, context)
	env.Cursor = env.Limit - v_23
	var v_24 = env.Limit - env.Cursor
	r_step5f(env, context)
	env.Cursor = env.Limit - v_24
	var v_25 = env.Limit - env.Cursor
	r_step5g(env, context)
	env.Cursor = env.Limit - v_25
	var v_26 = env.Limit - env.Cursor
	r_step5h(env, context)
	env.Cursor = env.Limit - v_26
	var v_27 = env.Limit - env.Cursor
	r_step5j(env, context)
	env.Cursor = env.Limit - v_27
	var v_28 = env.Limit - env.Cursor
	r_step5i(env, context)
	env.Cursor = env.Limit - v_28
	var v_29 = env.Limit - env.Cursor
	r_step5k(env, context)
	env.Cursor = env.Limit - v_29
	var v_30 = env.Limit - env.Cursor
	r_step5l(env, context)
	env.Cursor = env.Limit - v_30
	var v_31 = env.Limit - env.Cursor
	r_step5m(env, context)
	env.Cursor = env.Limit - v_31
	var v_32 = env.Limit - env.Cursor
	r_step6(env, context)
	env.Cursor = env.Limit - v_32
	var v_33 = env.Limit - env.Cursor
	r_step7(env, context)
	env.Cursor = env.Limit - v_33
	env.Cursor = env.LimitBackward
	return true
}
